import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Provider as TooltipProvider } from "@radix-ui/react-tooltip";
import Provider from "./provider"; // <-- Import your provider
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <TooltipProvider>
            <Provider>  
              {children}
              <Toaster/>
              </Provider>
          </TooltipProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
